UBOOT_PATH = $(PROJECT_BASE_PATH)/uboot-imx
UBOOT_TARGET = u-boot-dtb.imx

UBOOT_BIN_PATH = $(UBOOT_PATH)/u-boot-dtb.imx

UBOOT_INSTALL_PATH = $(DIST_PATH)

.PHONY: all install clean

all:
	$(HIDE)$(MAKE) -C $(UBOOT_PATH) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE)

install: all
	$(HIDE)mkdir -p $(UBOOT_INSTALL_PATH)
	$(HIDE)cp $(UBOOT_BIN_PATH) $(UBOOT_INSTALL_PATH)/$(UBOOT_TARGET)

clean:
	$(HIDE)$(MAKE) -C $(UBOOT_PATH) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) clean